package com.example.subcompose.model

import com.example.subcompose.R

object FakeMenuDataSource {
    val dummyMenu = listOf(
        Menu(1, R.drawable.bakso_bakar, "Bakso Bakar","Snack","Bakso bakar adalah variasi unik dari hidangan bakso tradisional Indonesia. Proses pembakarannya memberikan sentuhan berbeda pada rasa dan tekstur bakso. Bakso yang biasanya direbus, kali ini dibakar setelah dipanggang dengan saus atau bumbu khusus. Hasilnya adalah bakso yang memiliki aroma bakaran yang lezat, dengan lapisan luar yang krispi dan rasa yang kaya karena proses pemanggangan.",8000),
        Menu(2, R.drawable.chicken_karage, "Chicken Karage","Makanan","Chicken karaage adalah hidangan populer dari Jepang yang terkenal karena potongan ayam yang digoreng hingga krispi dan gurih di luar, sementara dagingnya tetap lembut dan juicy di dalam. Proses memasaknya melibatkan merendam potongan-potongan ayam dalam campuran bumbu, seperti kecap asin, mirin, dan bawang putih, sebelum melapisi mereka dengan tepung dan menggoreng hingga kecokelatan.",15000),
        Menu(3, R.drawable.mie, "Mie Special","Makanan","Indomie spesial adalah varian mi instan dari merek terkenal Indonesia, Indomie. Mi ini memiliki cita rasa yang khas dan berbeda, membuatnya menjadi pilihan istimewa bagi pencinta mi instan. Indomie spesial biasanya disajikan dengan bumbu dan tambahan lain yang membuatnya lebih lezat dan istimewa dibandingkan dengan varian mi instan lainnya.",7000),
        Menu(4, R.drawable.chicken_wings, "Chiken Wings","Snack","Chicken wings, atau sayap ayam, adalah potongan daging ayam yang populer dan sering diolah menjadi hidangan lezat. Dengan dua bagian utama, yaitu drumette dan flat, chicken wings sering diaplikasikan dengan berbagai macam bumbu dan saus sebelum diolah. Proses paling umum adalah menggoreng, memanggang, atau menggril.",20000),
        Menu(5, R.drawable.mie_secret, "Mie Secret","Makanan","Indomie yang dimasak dengan sentuhan spesial sering kali melibatkan penggunaan bumbu tambahan yang tidak biasa, memberikan cita rasa yang lebih kaya dan berbeda. Bumbu tambahan ini mungkin terdiri dari rempah-rempah, saus, atau bahan lain yang diracik secara khusus untuk menciptakan pengalaman makan yang istimewa.",9000),
        Menu(6, R.drawable.potato_wedges, "Potato Wedges","Snack","Potato wedges adalah irisan kentang besar yang dipotong seperti segitiga atau cincin, kemudian dipanggang atau digoreng hingga menjadi renyah di luar dan lembut di dalam. Hidangan ini populer sebagai camilan atau pendamping dalam berbagai acara dan restoran.",12000),
        Menu(7, R.drawable.nanban, "Nanban Rice","Makanan","Nanban Rice adalah hidangan Jepang yang terdiri dari nasi yang dihidangkan bersama potongan daging yang digoreng. Potongan daging, seringkali ayam, dipanggang atau digoreng hingga kecokelatan dan kemudian dilumuri dengan saus nanban yang unik.",18000),
        Menu(8, R.drawable.telur_crispy, "Telur Crispy","Snack","Telur crispy adalah telur yang dimasak dengan cara tertentu sehingga kulitnya menjadi renyah dan krispi, sementara kuning telurnya tetap lembut atau setidaknya tidak sepenuhnya matang. Metode memasak yang umum digunakan untuk mencapai efek crispy ini adalah dengan menggoreng telur dalam minyak panas atau dengan menggunakan teknik deep frying.",9000),
        Menu(9, R.drawable.coffee_breeze, "Coffee Breeze","Minuman","Minuman kopi dengan campuran sedikit soda seringkali disebut sebagai \"coffee soda\" atau \"sparkling coffee.\" Ini adalah variasi yang menarik dari minuman kopi yang biasanya terdiri dari kopi dingin atau espresso yang dicampur dengan air soda berkarbonasi. ",15000),
        Menu(10, R.drawable.coffee_milk, "Coffee Milk","Minuman","Coffee Milk adalah minuman sederhana yang terdiri dari kopi yang dicampur dengan susu. Proses pembuatannya melibatkan penyeduhan kopi atau espresso dan kemudian mencampurnya dengan susu. Kombinasi ini menciptakan minuman dengan rasa kopi yang khas dan kelembutan susu.",13000),
        Menu(11, R.drawable.lemon_tea, "Lemon Tea","Minuman","Lemon tea adalah minuman yang terbuat dari campuran teh dan perasan atau irisan lemon. Ini adalah minuman yang umum di seluruh dunia dan sering dijadikan sebagai pilihan menyegarkan, terutama saat cuaca panas.",8000),
        Menu(12, R.drawable.monaya, "Monaya","Minuman","Minuman ini biasanya dimulai dengan mencampurkan sirup, yang bisa berupa sirup buah-buahan atau sirup yang diberi rasa tertentu, dengan air. Kemudian, tambahkan perasan lemon untuk memberikan rasa asam dan aroma segar yang khas.",12000),
        Menu(13, R.drawable.susu_dewa, "Susu Dewa","Minuman","minuman yang terbuat dari susu yang di-blend bersama dengan biskuit Oreo. Proses pembuatannya melibatkan mencampurkan susu dengan potongan-potongan Oreo, baik yang sudah hancur atau yang masih utuh, dan kemudian di-blend hingga mencapai konsistensi yang halus dan krimi.",13000),
        Menu(14, R.drawable.viola, "Viola","Minuman","Soda sirup terbuat dari mencampurkan sirup dengan air soda berkarbonasi. Sirup yang digunakan bisa bervariasi, mulai dari sirup buah-buahan seperti stroberi, raspberry, atau jeruk, hingga sirup rasa lainnya seperti vanila, karamel, atau mint.",14000)
    )
}